services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app