name: ci.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and_security_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências
        run: poetry install

      - name: Rodar Ruff (Linter)
        run: poetry run ruff check .

      - name: Rodar Bandit (Segurança)
        run: poetry run bandit -r .

      - name: Rodar Safety
        run: poetry run safety check
